// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqCAm__9h0bxheHOS4nguVaLCWLBqAAh0',
    appId: '1:278841279550:android:88acc0916158c325cafd6f',
    messagingSenderId: '278841279550',
    projectId: 'windchat-sayak',
    storageBucket: 'windchat-sayak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBk7dhwAUf76eUuhPl7qFoa2R9psnnUU',
    appId: '1:278841279550:ios:7415dca463067e88cafd6f',
    messagingSenderId: '278841279550',
    projectId: 'windchat-sayak',
    storageBucket: 'windchat-sayak.appspot.com',
    androidClientId: '278841279550-ddfhn9obmpcqra8itqg02fr0ikm3b56r.apps.googleusercontent.com',
    iosClientId: '278841279550-a2hm9rlojnf92djphpltmv0pv0fbom0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.windchat',
  );
}
